// packages/workflow-sdk/examples/vue-element-plus/src/components/DataViewer.vue
<template>
  <el-card style="max-width: 600px; margin: 24px auto">
    <template #header>
      <div style="display: flex; justify-content: space-between; align-items: center">
        <span>敏感数据</span>
        <el-tag type="success">已授权</el-tag>
      </div>
    </template>
    <el-descriptions :column="1" border>
      <el-descriptions-item label="请求 ID">{{ requestId }}</el-descriptions-item>
      <el-descriptions-item label="获取时间">
        {{ new Date(fetchedAt).toLocaleString('zh-CN') }}
      </el-descriptions-item>
      <el-descriptions-item label="内容">
        <div style="white-space: pre-wrap">{{ secretData }}</div>
      </el-descriptions-item>
    </el-descriptions>
  </el-card>
</template>

<script setup lang="ts">
defineProps<{
  secretData: string
  fetchedAt: number
  requestId: string
}>()
</script>

// packages/workflow-sdk/examples/react-antd/src/components/DataViewer.tsx
import React from 'react'
import { Card, Descriptions, Typography, Tag } from 'antd'

interface DataViewerProps {
    secretData: string
    fetchedAt: number
    requestId: string
}

export function DataViewer({ secretData, fetchedAt, requestId }: DataViewerProps) {
    return (
        <Card title="敏感数据" style={{ maxWidth: 600, margin: '24px auto' }} extra={<Tag color="green">已授权</Tag>}>
            <Descriptions column={1} bordered>
                <Descriptions.Item label="请求 ID">{requestId}</Descriptions.Item>
                <Descriptions.Item label="获取时间">{new Date(fetchedAt).toLocaleString('zh-CN')}</Descriptions.Item>
                <Descriptions.Item label="内容">
                    <Typography.Paragraph copyable style={{ margin: 0, whiteSpace: 'pre-wrap' }}>
                        {secretData}
                    </Typography.Paragraph>
                </Descriptions.Item>
            </Descriptions>
        </Card>
    )
}
