// packages/workflow-sdk/examples/vue-element-plus/src/components/VerifyForm.vue
<template>
  <div style="max-width: 400px; margin: 24px auto">
    <h3>身份验证</h3>
    <p style="color: #909399">请求 ID: {{ requestId }}</p>
    <p>
      请输入验证码以查看敏感数据。正确验证码：<el-tag>123456</el-tag>
    </p>
    <el-input
      v-model="code"
      placeholder="请输入 6 位验证码"
      maxlength="6"
      size="large"
      @keyup.enter="handleSubmit"
    >
      <template #append>
        <el-button :loading="loading" @click="handleSubmit">验证</el-button>
      </template>
    </el-input>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{
  requestId: string
  loading: boolean
}>()

const emit = defineEmits<{
  submit: [code: string]
}>()

const code = ref('')

function handleSubmit() {
  if (code.value.trim()) {
    emit('submit', code.value.trim())
  }
}
</script>

// packages/workflow-sdk/examples/react-antd/src/components/VerifyForm.tsx
import React, { useState } from 'react'
import { Form, Input, Button, Space, Typography } from 'antd'

export interface VerifyFormProps {
    requestId: string
    onSubmit: (code: string) => void
    loading: boolean
}

export function VerifyForm({ requestId, onSubmit, loading }: VerifyFormProps) {
    const [code, setCode] = useState('')

    return (
        <div style={{ maxWidth: 400, margin: '24px auto' }}>
            <Typography.Title level={4}>身份验证</Typography.Title>
            <Typography.Paragraph type="secondary">请求 ID: {requestId}</Typography.Paragraph>
            <Typography.Paragraph>
                请输入验证码以查看敏感数据。正确验证码：<Typography.Text code>123456</Typography.Text>
            </Typography.Paragraph>
            <Form onFinish={() => onSubmit(code)}>
                <Form.Item rules={[{ required: true, message: '请输入验证码' }]}>
                    <Space.Compact style={{ width: '100%' }}>
                        <Input
                            placeholder="请输入 6 位验证码"
                            value={code}
                            onChange={(e) => setCode(e.target.value)}
                            maxLength={6}
                            size="large"
                        />
                        <Button type="primary" htmlType="submit" loading={loading} size="large">
                            验证
                        </Button>
                    </Space.Compact>
                </Form.Item>
            </Form>
        </div>
    )
}
